/**
 * Docker Compose — service catalog (adapter).
 *
 * The version truth lives in `~/registry`. This module re-exports the
 * registry entries in the historical `ServiceConfig` shape that
 * `generator.ts` and `ComposeGenerator.astro` already use, plus the
 * UI-only category metadata.
 *
 * To add a new service: drop a seed in `src/registry/seeds/` and run
 * `npm run sync:registry`. Do not edit this file.
 */

import { listServices } from "~/registry";
import type { ServiceDefinition, ServiceCategory } from "~/registry";

// ── Re-exports for UI consumers ─────────────────────────────────
export { getService, listServices, resolveVersion, registryMeta } from "~/registry";
export type { ServiceDefinition, ServiceCategory, VersionSelection, ResolvedVersion, TagInfo } from "~/registry";

// ── Legacy types (kept for back-compat with the generator + UI) ─
export type PortMapping = { host: number; container: number; protocol?: "tcp" | "udp" };
export type VolumeMount = { host: string; container: string; readOnly?: boolean };
export type EnvVar = { key: string; value: string };
export type ResourceLimit = { cpus?: string; memory?: string };

export interface ServiceConfig {
  name: string;
  label: string;
  category: ServiceCategory;
  description: string;
  emoji: string;
  image: string;
  defaultTag: string;
  defaultPorts: { host: number; container: number; protocol?: "tcp" | "udp" }[];
  defaultVolumes: { host: string; container: string; readOnly?: boolean }[];
  defaultEnv: { key: string; value: string }[];
  hasHealthcheck: boolean;
  healthcheckCmd?: string[];
  healthcheckPath?: string;
  healthcheckPort?: number;
  defaultRestart: "no" | "always" | "on-failure" | "unless-stopped";
  defaultCommand?: string[];
  dependsOn?: string[];
  createsVolumes?: string[];
  isApp?: boolean;
  tags?: string[];
  /** Available tags for the VersionPicker. */
  availableTags: { tag: string; isFloating?: boolean; publishedAt?: string }[];
  /** Latest stable as of last sync. */
  latestTag: string;
  /** True if image is on an external registry (ghcr, elastic, quay, mcr). */
  externalRegistry?: "ghcr" | "quay" | "elastic" | "mcr";
}

const toServiceConfig = (svc: ServiceDefinition): ServiceConfig => ({
  name: svc.id,
  label: svc.label,
  category: svc.category,
  description: svc.description,
  emoji: svc.emoji,
  image: svc.image,
  defaultTag: svc.recommended,
  defaultPorts: [...svc.compose.ports],
  defaultVolumes: svc.compose.volumes.map((v) => ({ ...v })),
  defaultEnv: svc.compose.env.map((e) => ({ ...e })),
  hasHealthcheck: svc.compose.hasHealthcheck,
  healthcheckCmd: svc.compose.healthcheckCmd ? [...svc.compose.healthcheckCmd] : undefined,
  healthcheckPath: svc.compose.healthcheckPath,
  healthcheckPort: svc.compose.healthcheckPort,
  defaultRestart: svc.compose.defaultRestart,
  defaultCommand: svc.compose.defaultCommand ? [...svc.compose.defaultCommand] : undefined,
  dependsOn: svc.compose.dependsOn ? [...svc.compose.dependsOn] : undefined,
  createsVolumes: svc.compose.createsVolumes ? [...svc.compose.createsVolumes] : undefined,
  isApp: svc.compose.isApp,
  tags: [...svc.tags],
  availableTags: svc.availableTags.map((t) => ({ ...t })),
  latestTag: svc.latest,
  externalRegistry: svc.externalRegistry,
});

/** Pre-resolved compose defaults for the application service. */
const appConfig: ServiceConfig = {
  name: "app",
  label: "Application",
  category: "application",
  description: "Your application service — points to a Dockerfile build.",
  emoji: "🚀",
  image: "./Dockerfile",
  defaultTag: "latest",
  defaultPorts: [{ host: 3000, container: 3000 }],
  defaultVolumes: [{ host: "./app", container: "/app" }],
  defaultEnv: [{ key: "NODE_ENV", value: "production" }],
  hasHealthcheck: false,
  defaultRestart: "unless-stopped",
  isApp: true,
  availableTags: [],
  latestTag: "latest",
};

/** Map of all services the user can pick, keyed by id. */
export const SERVICES: Record<string, ServiceConfig> = (() => {
  const map: Record<string, ServiceConfig> = { app: appConfig };
  for (const svc of listServices()) {
    map[svc.id] = toServiceConfig(svc);
  }
  return map;
})();

export const SERVICE_LIST: ReadonlyArray<ServiceConfig> = Object.values(SERVICES);
export const SERVICE_IDS: ReadonlyArray<string> = Object.keys(SERVICES);

export const CATEGORY_LABELS: Record<ServiceCategory, string> = {
  application: "Application",
  database: "Databases",
  cache: "Cache",
  search: "Search",
  queue: "Message Queue",
  proxy: "Reverse Proxy",
  storage: "Storage",
  monitoring: "Monitoring",
  observability: "Observability",
  auth: "Auth",
  "ci-dev": "CI/CD",
};

export const CATEGORY_ORDER: ReadonlyArray<ServiceCategory> = [
  "application",
  "database",
  "cache",
  "search",
  "queue",
  "proxy",
  "storage",
  "monitoring",
  "observability",
  "auth",
  "ci-dev",
];
