/**
 * Microservice Builder — .env.example generator.
 *
 * For each service in the config, dump its env vars (excluding
 * secret-refs which are sourced from the secrets: block, not env)
 * grouped by service. Comments at the top explain usage.
 */

import type { MicroserviceConfig, EnvVar } from "./schema";

export const generateMicroserviceEnv = (cfg: MicroserviceConfig): string => {
  const lines: string[] = [];
  lines.push("# Generated by dockerfilegenerator.soumosarkar.online");
  lines.push("# Copy to .env and fill in real values before `docker compose up`.");
  lines.push("");

  // Group env vars by service id; skip secret-refs (those are in
  // the secrets: block, mounted to /run/secrets/).
  const grouped: Record<string, EnvVar[]> = {};
  for (const [id, svc] of Object.entries(cfg.services)) {
    const evs = (svc.envVars ?? []).filter((e) => (e.kind ?? "literal") !== "secret-ref");
    if (evs.length) grouped[id] = evs;
  }

  if (Object.keys(grouped).length === 0) {
    lines.push("# No environment variables defined.");
    lines.push("");
    return lines.join("\n");
  }

  for (const [id, evs] of Object.entries(grouped)) {
    lines.push(`# ── ${id} ─────────────────────────────────────`);
    for (const e of evs) {
      const k = e.key;
      const v = e.value ?? "";
      // Quote values that contain spaces or special chars
      if (/[\s#"']/.test(v) || v === "") {
        lines.push(`${k}="${v.replace(/"/g, '\\"')}"`);
      } else {
        lines.push(`${k}=${v}`);
      }
    }
    lines.push("");
  }

  // If there are file-source secrets, hint at where to put them.
  const fileSecrets = cfg.secrets.filter((s) => s.source === "file");
  if (fileSecrets.length) {
    lines.push("# ── Secrets (file-sourced) ───────────────────");
    for (const s of fileSecrets) {
      lines.push(`# Create ${s.file ?? `./secrets/${s.name}.txt`} with the secret value.`);
    }
    lines.push("");
  }

  return lines.join("\n");
};
