/**
 * Microservice Builder — README generator.
 *
 * Produces a project README that explains the generated layout
 * and how to run it.
 */

import type { MicroserviceConfig, ServiceOverride } from "./schema";

const SERVICE_CATEGORY_EMOJI: Record<string, string> = {
  application: "🚀",
  database: "🗄️",
  cache: "⚡",
  search: "🔍",
  queue: "📨",
  proxy: "🌐",
  storage: "📦",
  monitoring: "📈",
  auth: "🔐",
  observability: "🔭",
  "ci-dev": "🛠️",
};

const sectionFor = (svc: ServiceOverride): string => {
  const port = svc.ports?.[0];
  const lines: string[] = [];
  const emoji = SERVICE_CATEGORY_EMOJI[svc.category ?? "application"] ?? "•";
  lines.push(`### ${emoji} \`${svc.id}\``);
  if (svc.framework) lines.push(`- **Framework:** ${svc.framework}`);
  if (svc.ports?.length) {
    lines.push(`- **Ports:** ${svc.ports.map((p) => `${p.host}→${p.container}`).join(", ")}`);
  }
  if (svc.dependsOn?.length) {
    lines.push(`- **Depends on:** ${svc.dependsOn.map((d) => `\`${d}\``).join(", ")}`);
  }
  if (svc.profiles?.length) {
    lines.push(`- **Profiles:** ${svc.profiles.map((p) => `\`${p}\``).join(", ")}`);
  }
  if (port) lines.push(`- **URL:** http://localhost:${port.host}`);
  return lines.join("\n");
};

export const generateMicroserviceReadme = (cfg: MicroserviceConfig): string => {
  const lines: string[] = [];
  lines.push(`# ${cfg.projectName}`);
  lines.push("");
  if (cfg.description) {
    lines.push(cfg.description);
    lines.push("");
  }
  lines.push("Generated by [dockerfilegenerator.soumosarkar.online](https://dockerfilegenerator.soumosarkar.online).");
  lines.push("");

  // Architecture overview
  lines.push("## Architecture");
  lines.push("");
  const appIds = Object.keys(cfg.services).filter((id) => cfg.services[id].build || cfg.services[id].framework);
  const infraIds = Object.keys(cfg.services).filter((id) => !appIds.includes(id));
  if (appIds.length) {
    lines.push(`**Application services (${appIds.length}):** ${appIds.map((id) => `\`${id}\``).join(", ")}`);
  }
  if (infraIds.length) {
    lines.push(`**Infrastructure (${infraIds.length}):** ${infraIds.map((id) => `\`${id}\``).join(", ")}`);
  }
  lines.push("");

  // Service catalog
  lines.push("## Services");
  lines.push("");
  for (const id of Object.keys(cfg.services)) {
    lines.push(sectionFor(cfg.services[id]));
    lines.push("");
  }

  // Running
  lines.push("## Running locally");
  lines.push("");
  lines.push("```bash");
  lines.push("# Copy the example env and edit secrets");
  lines.push("cp .env.example .env");
  lines.push("");
  lines.push("# Build and start");
  lines.push(`docker compose -f ${cfg.composeFileName ?? "compose.yaml"} up -d --build`);
  lines.push("");
  lines.push("# Tail logs");
  lines.push(`docker compose -f ${cfg.composeFileName ?? "compose.yaml"} logs -f`);
  lines.push("```");
  lines.push("");

  // Profiles
  const allProfiles = new Set<string>();
  for (const svc of Object.values(cfg.services)) {
    for (const p of svc.profiles ?? []) allProfiles.add(p);
  }
  if (allProfiles.size) {
    lines.push("## Profiles");
    lines.push("");
    lines.push("Services tagged with profiles only start when the profile is selected:");
    lines.push("");
    lines.push("```bash");
    for (const p of allProfiles) {
      lines.push(`docker compose --profile ${p} up -d`);
    }
    lines.push("```");
    lines.push("");
  }

  // File layout
  lines.push("## File layout");
  lines.push("");
  lines.push("```");
  lines.push(`${cfg.projectName}/`);
  lines.push(`├── ${cfg.composeFileName ?? "compose.yaml"}      # This generator's main output`);
  lines.push("├── .env.example            # Environment template (copy to .env)");
  appIds.forEach((id) => {
    lines.push(`├── ${id}/`);
    lines.push("│   ├── Dockerfile");
    lines.push("│   └── .dockerignore");
  });
  lines.push("└── README.md               # This file");
  lines.push("```");
  lines.push("");

  return lines.join("\n");
};
