// AUTO-GENERATED by scripts/sync-registry.mjs
// Do not edit by hand — run `npm run sync:registry` to refresh.
// Last sync: 2026-06-07T04:50:34.952Z

import type { ServiceDefinition } from "./types";

export const REGISTRY: Readonly<Record<string, ServiceDefinition>> = {
  "elasticsearch": {
    "id": "elasticsearch",
    "label": "Elasticsearch",
    "description": "Distributed search and analytics engine.",
    "emoji": "🔍",
    "category": "search",
    "tags": [
      "search",
      "analytics",
      "olap"
    ],
    "image": "docker.elastic.co/elasticsearch/elasticsearch",
    "official": true,
    "externalRegistry": "elastic",
    "recommended": "8.13.0",
    "latest": "8.15.0",
    "versionSource": "manual",
    "compose": {
      "ports": [
        {
          "host": 9200,
          "container": 9200
        }
      ],
      "volumes": [
        {
          "host": "es_data",
          "container": "/usr/share/elasticsearch/data"
        }
      ],
      "env": [
        {
          "key": "discovery.type",
          "value": "single-node"
        },
        {
          "key": "xpack.security.enabled",
          "value": "false"
        },
        {
          "key": "ES_JAVA_OPTS",
          "value": "-Xms512m -Xmx512m"
        }
      ],
      "hasHealthcheck": true,
      "healthcheckCmd": [
        "curl",
        "-fsS",
        "http://localhost:9200/_cluster/health"
      ],
      "defaultRestart": "unless-stopped",
      "createsVolumes": [
        "es_data"
      ]
    },
    "availableTags": [
      {
        "tag": "8.15.0",
        "isFloating": false,
        "publishedAt": "2025-01-10T00:00:00Z"
      },
      {
        "tag": "8.13.0",
        "isFloating": false,
        "publishedAt": "2024-10-30T00:00:00Z"
      },
      {
        "tag": "8.10.0",
        "isFloating": false,
        "publishedAt": "2024-04-01T00:00:00Z"
      },
      {
        "tag": "8.0.0",
        "isFloating": false,
        "publishedAt": "2024-02-10T00:00:00Z"
      }
    ]
  },
  "kafka": {
    "id": "kafka",
    "label": "Kafka",
    "description": "Distributed event streaming platform.",
    "emoji": "🟧",
    "category": "queue",
    "tags": [
      "queue",
      "streaming",
      "event"
    ],
    "image": "apache/kafka",
    "official": true,
    "recommended": "3.9.2",
    "latest": "3.9.2",
    "versionSource": "manual",
    "compose": {
      "ports": [
        {
          "host": 9092,
          "container": 9092
        }
      ],
      "volumes": [
        {
          "host": "kafka_data",
          "container": "/var/lib/kafka/data"
        }
      ],
      "env": [
        {
          "key": "KAFKA_NODE_ID",
          "value": "1"
        },
        {
          "key": "KAFKA_PROCESS_ROLES",
          "value": "broker,controller"
        },
        {
          "key": "KAFKA_LISTENERS",
          "value": "PLAINTEXT://:9092,CONTROLLER://:9093"
        },
        {
          "key": "KAFKA_ADVERTISED_LISTENERS",
          "value": "PLAINTEXT://kafka:9092"
        },
        {
          "key": "KAFKA_CONTROLLER_LISTENER_NAMES",
          "value": "CONTROLLER"
        },
        {
          "key": "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP",
          "value": "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
        },
        {
          "key": "KAFKA_INTER_BROKER_LISTENER_NAME",
          "value": "PLAINTEXT"
        },
        {
          "key": "KAFKA_CONTROLLER_QUORUM_VOTERS",
          "value": "1@kafka:9093"
        },
        {
          "key": "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR",
          "value": "1"
        },
        {
          "key": "KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR",
          "value": "1"
        },
        {
          "key": "KAFKA_TRANSACTION_STATE_LOG_MIN_ISR",
          "value": "1"
        },
        {
          "key": "KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS",
          "value": "0"
        },
        {
          "key": "CLUSTER_ID",
          "value": "MkU3OEVBNTcwNTJENDM2Qk"
        }
      ],
      "hasHealthcheck": true,
      "healthcheckCmd": [
        "CMD-SHELL",
        "kafka-broker-api-versions.sh --bootstrap-server localhost:9092 >/dev/null 2>&1"
      ],
      "defaultRestart": "unless-stopped",
      "createsVolumes": [
        "kafka_data"
      ]
    },
    "availableTags": [
      {
        "tag": "3.9.2",
        "isFloating": false,
        "publishedAt": "2026-02-15T00:00:00Z"
      },
      {
        "tag": "3.9.1",
        "isFloating": false,
        "publishedAt": "2026-01-20T00:00:00Z"
      },
      {
        "tag": "3.9.0",
        "isFloating": false,
        "publishedAt": "2025-12-05T00:00:00Z"
      },
      {
        "tag": "3.8.1",
        "isFloating": false,
        "publishedAt": "2025-09-15T00:00:00Z"
      },
      {
        "tag": "3.7.2",
        "isFloating": false,
        "publishedAt": "2025-04-10T00:00:00Z"
      }
    ]
  },
  "mariadb": {
    "id": "mariadb",
    "label": "MariaDB",
    "description": "Drop-in MySQL replacement with improved performance.",
    "emoji": "🦭",
    "category": "database",
    "tags": [
      "sql",
      "relational",
      "mysql-compatible"
    ],
    "image": "mariadb",
    "official": true,
    "recommended": "11.4",
    "latest": "11.4",
    "versionSource": "sync",
    "compose": {
      "ports": [
        {
          "host": 3306,
          "container": 3306
        }
      ],
      "volumes": [
        {
          "host": "mariadb_data",
          "container": "/var/lib/mysql"
        }
      ],
      "env": [
        {
          "key": "MARIADB_ROOT_PASSWORD",
          "value": "changeme"
        },
        {
          "key": "MARIADB_DATABASE",
          "value": "app"
        }
      ],
      "hasHealthcheck": true,
      "healthcheckCmd": [
        "healthcheck.sh",
        "--connect",
        "--innodb_initialized"
      ],
      "defaultRestart": "unless-stopped",
      "createsVolumes": [
        "mariadb_data"
      ]
    },
    "availableTags": [
      {
        "tag": "11.4",
        "isFloating": false
      }
    ]
  },
  "minio": {
    "id": "minio",
    "label": "MinIO",
    "description": "S3-compatible object storage.",
    "emoji": "🪣",
    "category": "storage",
    "tags": [
      "s3",
      "object-storage"
    ],
    "image": "minio/minio",
    "official": true,
    "recommended": "RELEASE.2024-10-13T13-34-11Z",
    "latest": "RELEASE.2024-10-13T13-34-11Z",
    "versionSource": "sync",
    "compose": {
      "ports": [
        {
          "host": 9000,
          "container": 9000
        },
        {
          "host": 9001,
          "container": 9001
        }
      ],
      "volumes": [
        {
          "host": "minio_data",
          "container": "/data"
        }
      ],
      "env": [
        {
          "key": "MINIO_ROOT_USER",
          "value": "minioadmin"
        },
        {
          "key": "MINIO_ROOT_PASSWORD",
          "value": "changeme"
        }
      ],
      "hasHealthcheck": true,
      "healthcheckCmd": [
        "curl",
        "-f",
        "http://localhost:9000/minio/health/live"
      ],
      "defaultRestart": "unless-stopped",
      "defaultCommand": [
        "server",
        "/data",
        "--console-address",
        ":9001"
      ],
      "createsVolumes": [
        "minio_data"
      ]
    },
    "availableTags": [
      {
        "tag": "RELEASE.2025-09-07T16-13-09Z-cpuv1",
        "publishedAt": "2025-09-07T18:49:28.309046Z",
        "sizeBytes": 59306028,
        "digest": "sha256:13582eff79c6605a2d315bdd0e70164142ea7e98fc8411e9e10d089502a6d883",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-09-07T16-13-09Z",
        "publishedAt": "2025-09-07T18:45:34.689393Z",
        "sizeBytes": 57537266,
        "digest": "sha256:14cea493d9a34af32f524e538b8346cf79f3321eff8e708c1e2960462bd8936e",
        "isFloating": false
      },
      {
        "tag": "latest-cicd",
        "publishedAt": "2025-09-07T18:44:58.493588Z",
        "sizeBytes": 57537266,
        "digest": "sha256:14cea493d9a34af32f524e538b8346cf79f3321eff8e708c1e2960462bd8936e",
        "isFloating": false
      },
      {
        "tag": "latest",
        "publishedAt": "2025-09-07T18:44:54.143784Z",
        "sizeBytes": 57537266,
        "digest": "sha256:14cea493d9a34af32f524e538b8346cf79f3321eff8e708c1e2960462bd8936e",
        "isFloating": true
      },
      {
        "tag": "RELEASE.2025-07-23T15-54-02Z-cpuv1",
        "publishedAt": "2025-07-23T20:13:17.938805Z",
        "sizeBytes": 59210686,
        "digest": "sha256:7330be2e7320a7a699b36f72bd06a94d8a21ec9f6f397345d9c38fc6751141f5",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-07-23T15-54-02Z",
        "publishedAt": "2025-07-23T20:10:41.726706Z",
        "sizeBytes": 57463056,
        "digest": "sha256:d249d1fb6966de4d8ad26c04754b545205ff15a62e4fd19ebd0f26fa5baacbc0",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-07-18T21-56-31Z-cpuv1",
        "publishedAt": "2025-07-18T23:55:58.387334Z",
        "sizeBytes": 59208861,
        "digest": "sha256:6b873fc70cdba5f20476f748b2e1c46183e9d0271c7a4e77458393e63fbe6b4e",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-07-18T21-56-31Z",
        "publishedAt": "2025-07-18T23:53:28.207135Z",
        "sizeBytes": 57461147,
        "digest": "sha256:da0fe26595711d0fb93dd28e24552520f68897195f4a23f5a17ffa9924ec3fac",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-06-13T11-33-47Z-cpuv1",
        "publishedAt": "2025-06-23T20:56:14.718187Z",
        "sizeBytes": 59761263,
        "digest": "sha256:ad8a8318847c0bb7dcfe59caf407f12fad6f387bb66386ee772c4704f0a48d50",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-06-13T11-33-47Z",
        "publishedAt": "2025-06-23T20:53:43.226597Z",
        "sizeBytes": 57458333,
        "digest": "sha256:064117214caceaa8d8a90ef7caa58f2b2aeb316b5156afe9ee8da5b4d83e12c8",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-05-24T17-08-30Z-cpuv1",
        "publishedAt": "2025-05-24T21:43:54.970472Z",
        "sizeBytes": 59661679,
        "digest": "sha256:e05d6141e56326024cb8049bc9a594e26f7ac79a4505e9465c211b522b91461a",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-05-24T17-08-30Z",
        "publishedAt": "2025-05-24T21:41:00.930713Z",
        "sizeBytes": 57359846,
        "digest": "sha256:a616cd8f37758b0296db62cc9e6af05a074e844cc7b5c0a0e62176d73828d440",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-04-22T22-12-26Z-cpuv1",
        "publishedAt": "2025-04-22T22:43:15.952235Z",
        "sizeBytes": 61644593,
        "digest": "sha256:8494c615f45cd6726f048dce162da5826582c2ce67d420428200d9d3cccf6e25",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-04-22T22-12-26Z",
        "publishedAt": "2025-04-22T22:39:10.756204Z",
        "sizeBytes": 59333042,
        "digest": "sha256:a1ea29fa28355559ef137d71fc570e508a214ec84ff8083e39bc5428980b015e",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-04-08T15-41-24Z-cpuv1",
        "publishedAt": "2025-04-08T19:49:48.030695Z",
        "sizeBytes": 61558382,
        "digest": "sha256:8a4b0c8b1021dc74bcaf5757cb0c3dc098967e7581f096459831d9a1c0a53603",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-04-08T15-41-24Z",
        "publishedAt": "2025-04-08T19:44:53.235554Z",
        "sizeBytes": 59246820,
        "digest": "sha256:8834ae47a2de3509b83e0e70da9369c24bbbc22de42f2a2eddc530eee88acd1b",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2023-12-02T10-51-33Z.hotfix.d45db9b16",
        "publishedAt": "2025-04-08T16:41:01.29405Z",
        "sizeBytes": 54000531,
        "digest": "sha256:a7faf7122ce94ad135a2d993d11231ab1d6ed85eea00df2d1e68287ee3b67e37",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-04-03T14-56-28Z-cpuv1",
        "publishedAt": "2025-04-03T19:05:53.187576Z",
        "sizeBytes": 61545769,
        "digest": "sha256:091341fd16644849bf52ca8f96de2bbf426d6b9b8b10d31933a563edfc406428",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-04-03T14-56-28Z",
        "publishedAt": "2025-04-03T19:02:44.35934Z",
        "sizeBytes": 59233250,
        "digest": "sha256:a640662d97632f7b94e9dee8cbb7da5c20db24879725cb4fac36f1e220cd528a",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-03-12T18-04-18Z-cpuv1",
        "publishedAt": "2025-03-12T18:36:35.80623Z",
        "sizeBytes": 61351082,
        "digest": "sha256:3166e27a12c2a4ab5be28fd328ef8243635c1ae36c46060d962f704f5618416b",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-03-12T18-04-18Z",
        "publishedAt": "2025-03-12T18:33:21.457138Z",
        "sizeBytes": 59133553,
        "digest": "sha256:46b3009bf7041eefbd90bd0d2b38c6ddc24d20a35d609551a1802c558c1c958f",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-02-28T09-55-16Z",
        "publishedAt": "2025-02-28T19:00:45.933034Z",
        "sizeBytes": 58781239,
        "digest": "sha256:a929054ae025fa7997857cd0e2a2e3029238e31ad89877326dc032f4c1a14259",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-02-28T09-55-16Z-cpuv1",
        "publishedAt": "2025-02-28T18:32:39.376505Z",
        "sizeBytes": 61026677,
        "digest": "sha256:6053f20bd03b2473563e7e066716fa55f004820f173fb8c152fb96d01312eb50",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-02-18T16-25-55Z-cpuv1",
        "publishedAt": "2025-02-18T21:14:38.906148Z",
        "sizeBytes": 61078154,
        "digest": "sha256:0b5ecc30b114189bd01618b6093aa39d5822bfef3ddab2c8111658862ee4e156",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-02-18T16-25-55Z",
        "publishedAt": "2025-02-18T21:12:08.83797Z",
        "sizeBytes": 58775028,
        "digest": "sha256:1df91be8d6a6146001cd6be2569a12785a8ece583b511f56ebed08f1e65d3611",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-02-07T23-21-09Z-cpuv1",
        "publishedAt": "2025-02-08T21:12:16.948831Z",
        "sizeBytes": 60969395,
        "digest": "sha256:91b7a4fb14d00116f9b32005461c36cf54c8cf3c408b9dceab50fce295651574",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-02-07T23-21-09Z",
        "publishedAt": "2025-02-08T21:09:43.425175Z",
        "sizeBytes": 58663886,
        "digest": "sha256:640c22768ed5dbc92eacc14502a1b06a1c708fa60431345c78dfc22917062e93",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-02-03T21-03-04Z-cpuv1",
        "publishedAt": "2025-02-04T07:08:25.936373Z",
        "sizeBytes": 60950948,
        "digest": "sha256:247b3ab5a7c817f2b9d4fe6b7261aa71c016da447c14d9e1f8fcfdf1fc9d2480",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-02-03T21-03-04Z",
        "publishedAt": "2025-02-04T07:04:46.28706Z",
        "sizeBytes": 58645856,
        "digest": "sha256:a62e44a7db506b8ed114a44e67b4996c4f1ecca981d9c6e40aa2581334999313",
        "isFloating": false
      },
      {
        "tag": "RELEASE.2025-01-20T14-49-07Z-cpuv1",
        "publishedAt": "2025-01-21T10:06:06.71791Z",
        "sizeBytes": 60861842,
        "digest": "sha256:14b7076ca85a8a39926338bed615445c377f1a9dad5142aebe1458ce37e27dbf",
        "isFloating": false
      }
    ]
  },
  "mongodb": {
    "id": "mongodb",
    "label": "MongoDB",
    "description": "Document-oriented NoSQL database.",
    "emoji": "🍃",
    "category": "database",
    "tags": [
      "nosql",
      "document"
    ],
    "image": "mongo",
    "official": true,
    "recommended": "8",
    "latest": "8",
    "versionSource": "sync",
    "compose": {
      "ports": [
        {
          "host": 27017,
          "container": 27017
        }
      ],
      "volumes": [
        {
          "host": "mongo_data",
          "container": "/data/db"
        }
      ],
      "env": [
        {
          "key": "MONGO_INITDB_ROOT_USERNAME",
          "value": "root"
        },
        {
          "key": "MONGO_INITDB_ROOT_PASSWORD",
          "value": "changeme"
        }
      ],
      "hasHealthcheck": true,
      "healthcheckCmd": [
        "mongosh",
        "--eval",
        "db.adminCommand('ping')"
      ],
      "defaultRestart": "unless-stopped",
      "createsVolumes": [
        "mongo_data"
      ]
    },
    "availableTags": [
      {
        "tag": "8",
        "isFloating": false
      }
    ]
  },
  "mysql": {
    "id": "mysql",
    "label": "MySQL",
    "description": "Popular open source relational database.",
    "emoji": "🐬",
    "category": "database",
    "tags": [
      "sql",
      "relational"
    ],
    "image": "mysql",
    "official": true,
    "recommended": "8.4",
    "latest": "8.4",
    "versionSource": "sync",
    "compose": {
      "ports": [
        {
          "host": 3306,
          "container": 3306
        }
      ],
      "volumes": [
        {
          "host": "mysql_data",
          "container": "/var/lib/mysql"
        }
      ],
      "env": [
        {
          "key": "MYSQL_ROOT_PASSWORD",
          "value": "changeme"
        },
        {
          "key": "MYSQL_DATABASE",
          "value": "app"
        }
      ],
      "hasHealthcheck": true,
      "healthcheckCmd": [
        "mysqladmin",
        "ping",
        "-h",
        "localhost"
      ],
      "defaultRestart": "unless-stopped",
      "createsVolumes": [
        "mysql_data"
      ]
    },
    "availableTags": [
      {
        "tag": "8.4",
        "isFloating": false
      }
    ]
  },
  "nginx": {
    "id": "nginx",
    "label": "Nginx",
    "description": "High-performance HTTP server and reverse proxy.",
    "emoji": "🌐",
    "category": "proxy",
    "tags": [
      "proxy",
      "http",
      "tls"
    ],
    "image": "nginx",
    "official": true,
    "recommended": "1.27-alpine",
    "latest": "1.27-alpine",
    "versionSource": "sync",
    "compose": {
      "ports": [
        {
          "host": 80,
          "container": 80
        },
        {
          "host": 443,
          "container": 443
        }
      ],
      "volumes": [
        {
          "host": "./nginx.conf",
          "container": "/etc/nginx/nginx.conf",
          "readOnly": true
        },
        {
          "host": "./html",
          "container": "/usr/share/nginx/html",
          "readOnly": true
        }
      ],
      "env": [],
      "hasHealthcheck": true,
      "healthcheckCmd": [
        "wget",
        "--spider",
        "-q",
        "http://localhost/"
      ],
      "defaultRestart": "unless-stopped"
    },
    "availableTags": [
      {
        "tag": "1.27-alpine",
        "isFloating": true
      }
    ]
  },
  "postgres": {
    "id": "postgres",
    "label": "PostgreSQL",
    "description": "The world's most advanced open source relational database.",
    "emoji": "🐘",
    "category": "database",
    "tags": [
      "sql",
      "relational",
      "acid"
    ],
    "image": "postgres",
    "official": true,
    "recommended": "17-alpine",
    "latest": "17-alpine",
    "versionSource": "sync",
    "compose": {
      "ports": [
        {
          "host": 5432,
          "container": 5432
        }
      ],
      "volumes": [
        {
          "host": "postgres_data",
          "container": "/var/lib/postgresql/data"
        }
      ],
      "env": [
        {
          "key": "POSTGRES_USER",
          "value": "postgres"
        },
        {
          "key": "POSTGRES_PASSWORD",
          "value": "changeme"
        },
        {
          "key": "POSTGRES_DB",
          "value": "app"
        }
      ],
      "hasHealthcheck": true,
      "healthcheckCmd": [
        "pg_isready",
        "-U",
        "postgres"
      ],
      "defaultRestart": "unless-stopped",
      "createsVolumes": [
        "postgres_data"
      ]
    },
    "availableTags": [
      {
        "tag": "17-alpine",
        "isFloating": true
      }
    ]
  },
  "rabbitmq": {
    "id": "rabbitmq",
    "label": "RabbitMQ",
    "description": "Reliable message broker with AMQP and STOMP.",
    "emoji": "🐰",
    "category": "queue",
    "tags": [
      "queue",
      "amqp",
      "broker"
    ],
    "image": "rabbitmq",
    "official": true,
    "recommended": "4.0-management-alpine",
    "latest": "4.0-management-alpine",
    "versionSource": "sync",
    "compose": {
      "ports": [
        {
          "host": 5672,
          "container": 5672
        },
        {
          "host": 15672,
          "container": 15672
        }
      ],
      "volumes": [
        {
          "host": "rabbitmq_data",
          "container": "/var/lib/rabbitmq"
        }
      ],
      "env": [
        {
          "key": "RABBITMQ_DEFAULT_USER",
          "value": "guest"
        },
        {
          "key": "RABBITMQ_DEFAULT_PASS",
          "value": "guest"
        }
      ],
      "hasHealthcheck": true,
      "healthcheckCmd": [
        "rabbitmq-diagnostics",
        "ping"
      ],
      "defaultRestart": "unless-stopped",
      "createsVolumes": [
        "rabbitmq_data"
      ]
    },
    "availableTags": [
      {
        "tag": "4.0-management-alpine",
        "isFloating": true
      }
    ]
  },
  "redis": {
    "id": "redis",
    "label": "Redis",
    "description": "In-memory cache, message broker, and key-value store.",
    "emoji": "🔴",
    "category": "cache",
    "tags": [
      "cache",
      "kv",
      "broker"
    ],
    "image": "redis",
    "official": true,
    "recommended": "7.4-alpine",
    "latest": "7.4-alpine",
    "versionSource": "sync",
    "compose": {
      "ports": [
        {
          "host": 6379,
          "container": 6379
        }
      ],
      "volumes": [
        {
          "host": "redis_data",
          "container": "/data"
        }
      ],
      "env": [],
      "hasHealthcheck": true,
      "healthcheckCmd": [
        "redis-cli",
        "ping"
      ],
      "defaultRestart": "unless-stopped",
      "createsVolumes": [
        "redis_data"
      ]
    },
    "availableTags": [
      {
        "tag": "7.4-alpine",
        "isFloating": true
      }
    ]
  },
  "traefik": {
    "id": "traefik",
    "label": "Traefik",
    "description": "Modern reverse proxy with automatic service discovery.",
    "emoji": "🦌",
    "category": "proxy",
    "tags": [
      "proxy",
      "service-discovery",
      "letsencrypt"
    ],
    "image": "traefik",
    "official": true,
    "recommended": "v3.2",
    "latest": "v3.2",
    "versionSource": "sync",
    "compose": {
      "ports": [
        {
          "host": 80,
          "container": 80
        },
        {
          "host": 443,
          "container": 443
        },
        {
          "host": 8080,
          "container": 8080
        }
      ],
      "volumes": [
        {
          "host": "/var/run/docker.sock",
          "container": "/var/run/docker.sock",
          "readOnly": true
        },
        {
          "host": "./traefik",
          "container": "/etc/traefik"
        }
      ],
      "env": [],
      "hasHealthcheck": false,
      "defaultRestart": "unless-stopped"
    },
    "availableTags": [
      {
        "tag": "v3.2",
        "isFloating": false,
        "publishedAt": "2024-10-29T00:00:00Z"
      },
      {
        "tag": "v3.1",
        "isFloating": false,
        "publishedAt": "2024-04-29T00:00:00Z"
      },
      {
        "tag": "v2.11",
        "isFloating": false,
        "publishedAt": "2024-02-12T00:00:00Z"
      }
    ]
  }
} as const;
