/**
 * Service Registry — shared types.
 *
 * All Docker image metadata for the Compose Generator and Stack Builder
 * flows through this module. Image version truth lives in
 * `data.ts` (auto-generated by `scripts/sync-registry.mjs`).
 * Adding a new service = drop a seed in `seeds/`, run the sync script.
 */

export type ServiceCategory =
  | "application"
  | "database"
  | "cache"
  | "search"
  | "queue"
  | "proxy"
  | "storage"
  | "monitoring"
  | "observability"
  | "auth"
  | "ci-dev";

export interface PortMapping {
  readonly host: number;
  readonly container: number;
  readonly protocol?: "tcp" | "udp";
}

export interface VolumeMount {
  readonly host: string;
  readonly container: string;
  readonly readOnly?: boolean;
}

export interface EnvVar {
  readonly key: string;
  readonly value: string;
}

/** One tag/version discovered upstream. */
export interface TagInfo {
  readonly tag: string;
  readonly publishedAt?: string;
  readonly sizeBytes?: number;
  readonly digest?: string;
  /** True for `latest`, `stable`, `lts`, or `-alpine`/`-slim` floating tags. */
  readonly isFloating?: boolean;
  readonly platforms?: ReadonlyArray<"linux/amd64" | "linux/arm64" | "linux/arm/v7">;
}

/** Compose-specific defaults (the bits that aren't image registry concerns). */
export interface ComposeDefaults {
  readonly ports: ReadonlyArray<PortMapping>;
  readonly volumes: ReadonlyArray<VolumeMount>;
  readonly env: ReadonlyArray<EnvVar>;
  readonly hasHealthcheck: boolean;
  readonly healthcheckCmd?: ReadonlyArray<string>;
  readonly healthcheckPath?: string;
  readonly healthcheckPort?: number;
  readonly defaultRestart: "no" | "always" | "on-failure" | "unless-stopped";
  readonly defaultCommand?: ReadonlyArray<string>;
  readonly dependsOn?: ReadonlyArray<string>;
  readonly createsVolumes?: ReadonlyArray<string>;
  readonly isApp?: boolean;
}

/**
 * The runtime shape of a service entry. Constructed by the sync script
 * from a `ServiceSeed` + fetched tag data.
 */
export interface ServiceDefinition {
  readonly id: string;
  readonly label: string;
  readonly description: string;
  readonly emoji: string;
  readonly category: ServiceCategory;
  readonly tags: ReadonlyArray<string>;

  readonly image: string;
  readonly official: boolean;
  readonly externalRegistry?: "ghcr" | "quay" | "elastic" | "mcr";

  /** Pinned version shipped by default in generated output. Never `latest`. */
  readonly recommended: string;
  /** Highest stable release as of last sync. Surfaced in UI, not used as default. */
  readonly latest: string;
  /** Sorted DESC by publishedAt, trimmed to top 30. */
  readonly availableTags: ReadonlyArray<TagInfo>;

  /** How the recommended/latest tags were determined. */
  readonly versionSource?: "sync" | "manual";

  readonly compose: ComposeDefaults;
}

/**
 * Hand-authored seed — describes the *identity* of a service. The sync
 * script fills `availableTags` and refreshes `recommended` / `latest`.
 */
export interface ServiceSeed {
  readonly id: string;
  readonly label: string;
  readonly description: string;
  readonly emoji: string;
  readonly category: ServiceCategory;
  readonly tags: ReadonlyArray<string>;

  readonly image: string;
  readonly official: boolean;
  readonly externalRegistry?: "ghcr" | "quay" | "elastic" | "mcr";

  /** Hand-pinned; sync script leaves alone unless a static override exists. */
  readonly recommended: string;
  /** Hand-pinned; sync script may overwrite with network-discovered latest. */
  readonly latest: string;
  readonly versionSource: "sync" | "manual";

  readonly compose: ComposeDefaults;
}

/** What the user picks in the VersionPicker. */
export type VersionSelection =
  | { kind: "recommended" }
  | { kind: "latest" }
  | { kind: "pinned"; tag: string }
  | { kind: "custom"; tag: string };

/** Output of `resolveVersion()` — what the generator actually renders. */
export interface ResolvedVersion {
  readonly serviceId: string;
  readonly image: string;
  readonly tag: string;
  readonly source: "recommended" | "latest" | "pinned" | "custom";
  readonly isFloating: boolean;
}
